In [2]:
import numpy as np

In [3]:
# Create Numpy 1D Array

arr_1d = np.array([1,2,3,4])
arr_1d

array([1, 2, 3, 4])

In [4]:
# Numpy nD Array

arr_nd = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_nd

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# Check Type of Array

print(type(arr_1d))
print(type(arr_nd))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [9]:
# Check Dimension of Array

print(arr_1d.ndim)
print(arr_nd.ndim)

1
2


In [11]:
# Check Shape of Array

print(arr_1d.shape)
print(arr_nd.shape)

(4,)
(3, 3)


In [13]:
# Check size of Array (How Many Elements in Array)

print(arr_1d.size)
print(arr_nd.size)

4
9


In [15]:
# Check DataTYpe of Array's Elements

arr_str = np.array(['Av','Nee','Sh'])

print(arr_1d.dtype)
print(arr_str.dtype)

int32
<U3


In [23]:
# Ones Matrix

mx_once_simple = np.array([[1,1,1],[1,1,1],[1,1,1]])
print(mx_once_simple)

mx_ones = np.ones([3,3])
print(mx_ones)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [24]:
# Zeros Matrix

mx_zeros_simple = np.array([[0,0,0],[0,0,0],[0,0,0]])
print(mx_zeros_simple)

mx_zeros = np.zeros([3,3])
print(mx_zeros)


[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [33]:
# Empty Matrix

mx_empty = np.empty(4,dtype=bool)
mx_empty

array([ True,  True,  True,  True])

In [35]:
# arange function
arr1 = np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
# linspace Function

arr_2 = np.linspace(1,4,3)
arr_2

array([1. , 2.5, 4. ])

In [41]:
# reshape Function

arr3 = np.arange(1,10).reshape(3,3)
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
# ravel Function

arr4 = arr3.ravel()
arr4

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
# transpose Function

arr_5 = np.arange(1,10).reshape(3,3)
print(arr_5)

arr_t = arr_5.transpose()
print(arr_t)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


# Mathmatical Operations on Array

In [46]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [49]:
# Sum of Array

print(arr1+arr2)

print(np.add(arr1,arr2))

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [54]:
# Sub of Array

print(arr1 - arr2)

print(np.subtract(arr1,arr2))

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [56]:
# Multipication of Array

print(arr1 * arr2)

print(np.multiply(arr1,arr2))

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [58]:
# Matrix Multipication

print(arr1 @ arr2)

print(arr1.dot(arr2))

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [60]:
# Array Divide

print(arr1/arr2)

print(np.divide(arr1,arr2))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [61]:
# Maximum Value In Matrix

np.max(arr1)

9

In [62]:
# index of maximum value

np.argmax(arr1)

8

In [64]:
# maximum vale in row

np.max(arr1,axis=1)

array([3, 6, 9])

In [66]:
# Maximum value in column

np.max(arr1,axis=0)

array([7, 8, 9])

In [67]:
# Minimum Vaue in Matrix

np.min(arr1)

1

In [68]:
# Min Value in Coulumn'
np.min(arr1,axis=0)

array([1, 2, 3])

In [69]:
# Sum of All Element in Matrix

np.sum(arr1)

45

In [70]:
# sum of row vales

np.sum(arr1,axis=1)

array([ 6, 15, 24])

In [71]:
# sum of column value

np.sum(arr1,axis=0)

array([12, 15, 18])

In [72]:
# Mean of Matrix

np.mean(arr1)

5.0

In [75]:
# Sqrt in Matrix
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

# Array Slicing

In [76]:
ar1 = np.arange(1,101).reshape(10,10)
ar1

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [78]:
# Get First Value of Matrix

ar1[0,0]

1

In [79]:
# Get First Row

ar1[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
# Get All Columns and 1st row

ar1[0,0:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
# Get Selected Rows and Columns => 2,3,4 rows and 2,3,4 column

ar1[1:4,1:4]

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])

In [89]:
ar1

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [90]:
# Get All Rows and selected Columns

ar1[0:,1:5]

array([[ 2,  3,  4,  5],
       [12, 13, 14, 15],
       [22, 23, 24, 25],
       [32, 33, 34, 35],
       [42, 43, 44, 45],
       [52, 53, 54, 55],
       [62, 63, 64, 65],
       [72, 73, 74, 75],
       [82, 83, 84, 85],
       [92, 93, 94, 95]])

In [93]:
# Get All rows and all column

print(ar1[::])
print(ar1[0:,0:])
print(ar1[:,:])

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32

In [95]:
# Get Itemsize of element => Aciuired Memory

ar1.itemsize

4

# Concatenate and split Functions

In [96]:
ar1 = np.arange(1,17).reshape(4,4)
ar2 = np.arange(1,17).reshape(4,4)

print(ar1)
print(ar2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [98]:
# Concatenate Matrix

np.concatenate((ar1,ar2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [99]:
# concatenate Row Wise

np.concatenate((ar1,ar2),axis=1)

array([[ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12],
       [13, 14, 15, 16, 13, 14, 15, 16]])

In [100]:
# Concatenate Column Wise

np.concatenate((ar1,ar2),axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [102]:
# Split Array

# Split Matrix in 2 part

np.split(ar1,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [104]:
# Split 1D Array in multiple Part

ar1 = np.arange(1,10)
print(ar1)


# Split in 0 to 1, 2 to 5, 5 to 8 and 8 to so on indexes.
print(np.split(ar1,[2,5,8]))

[1 2 3 4 5 6 7 8 9]
[array([1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([9])]


# Random Sampling

In [105]:
# Get Random Value Array

np.random.random(1)

array([0.20659259])

In [106]:
np.random.random((3,3))

array([[0.11954189, 0.64749751, 0.62208333],
       [0.03116029, 0.47884028, 0.02868925],
       [0.52186971, 0.65633556, 0.83671951]])

In [108]:
# Get Integer Random Value

np.random.randint(1,10,(3,3))

array([[7, 1, 4],
       [7, 5, 2],
       [2, 3, 2]])

In [111]:
# seed Function => use for hold random value

np.random.seed(100)
np.random.randint(1,10,(4,4))

array([[9, 9, 4, 8],
       [8, 1, 5, 3],
       [6, 3, 3, 3],
       [2, 1, 9, 5]])

In [112]:
# Other Random Functions

np.random.rand(3,3)

array([[0.62431189, 0.52334774, 0.56229626],
       [0.00581719, 0.30742321, 0.95018431],
       [0.12665424, 0.07898787, 0.31135313]])

In [115]:
# Random Numbers negative and posetive

np.random.randn(3,3)

array([[ 0.22203428,  0.59829059, -1.75037385],
       [ 0.13330585, -1.31520994, -0.9374954 ],
       [ 0.38421144, -0.66167997,  2.58785597]])

In [118]:
# choice Function =>  use for choose Randomly from Array

ar1 = np.array([1,2,4,7,8])

np.random.choice(ar1)

1

In [121]:
# suffule Function => Use for Suffle The array Values

print(ar1)

print(np.random.permutation(ar1))

[1 2 4 7 8]
[2 7 1 4 8]


# String Operation in Numpy

In [123]:
str1 = "Hello Python"
str2 = "Hii Numpy"
print(str1)
print(str2)

Hello Python
Hii Numpy


In [126]:
# String Concatenation

np.char.add(str1,str2)

array('Hello PythonHii Numpy', dtype='<U21')

In [127]:
# Lower Case

np.char.lower(str1)

array('hello python', dtype='<U12')

In [129]:
# upper Case

np.char.upper(str2)

array('HII NUMPY', dtype='<U9')

In [130]:
# String in center => Give space from left side

np.char.center(str1,20)

array('    Hello Python    ', dtype='<U20')

In [131]:
# Split String

np.char.split(str1)

array(list(['Hello', 'Python']), dtype=object)

In [135]:
# join string

np.char.join("/",[str1,str2])

array(['H/e/l/l/o/ /P/y/t/h/o/n', 'H/i/i/ /N/u/m/p/y'], dtype='<U23')

In [140]:
# Replace String

np.char.replace(str1,'Hello','Django')

array('Django Python', dtype='<U13')

In [142]:
# Compare Strings

np.char.equal(str1,str2)

array(False)

In [145]:
# Count String Character

np.char.count(str1,'o')

array(2)

In [146]:
# Find Index of Substring

np.char.find(str1,'Python')

array(6)